"""Coarse2Contact v2: task-agnostic precision local skill layer."""

from .controllers import GuardedSlideController, GraspContactController, RecoveryFSM, RecoveryPhase, SkillControlResult
from .basin_recovery import (
    BasinLabel,
    BasinPullbackPolicyNet,
    BasinRecoveryConfig,
    BasinRecoveryDecision,
    BasinRecoveryMode,
    BasinRecoverySupervisor,
    BasinStateEstimatorNet,
    GraspOnlyBasinPullbackPolicy,
    VisualEvidenceClass,
    basin_recovery_feature_vector,
    classify_basin_label,
    classify_visual_evidence_for_basin,
)
from .datasets import DepthLocalizerJsonlDataset, ForceContactJsonlDataset, build_vocab as build_c2c_vocab
from .learned_force import ForceContactClassifierNet, LearnedForceClassifierAdapter, load_force_classifier_checkpoint
from .learned_localizer import (
    DepthGeometryLocalizerNet,
    GraspRecoveryHeadNet,
    GraspSkillHeadNet,
    GraspSkillPrediction,
    LearnedDepthLocalizerAdapter,
    RingFrameLocalizerNet,
    RingFramePrediction,
    load_ring_frame_localizer_checkpoint,
    load_depth_localizer_checkpoint,
    load_grasp_recovery_checkpoint,
)
from .recovery_augmentation import (
    augment_recovery_record,
    augment_recovery_record_replay,
    build_failure_replay_augmented_records,
    build_failure_replay_library,
    build_bucket_tail_replay_augmented_records,
    build_targeted_augmented_records,
    load_bias_template,
    select_hard_trajectories,
    select_focus_trajectories_by_bucket,
)
from .basin_state import BasinAxisCalibration, BasinStateCalibration, BasinStateEstimator, CalibratedGraspBasinEstimator, EstimatedBasinError, FrameRelabelBasinEstimator, ReplayBasinEstimator, ReplayBasinResult, load_basin_state_calibration_report
from .localizers import LocalGeometryError, RingGraspLocalizer, RingSpokeAlignLocalizer
from .mainline import (
    BASIN_RECOVERY_CLOSED_LOOP_REPORT,
    BASIN_RECOVERY_DATASET,
    RECOVERY_MAINLINE_CHECKPOINT,
    RECOVERY_MAINLINE_DATASET,
    RECOVERY_MAINLINE_NAME,
    RECOVERY_MAINLINE_REPORT,
    RUNTIME_FAILURE_DATASET_ROOT,
    RUNTIME_FAILURE_TRACE_ROOT,
)
from .specs import EntitySpec, PrecisionSkillSpec, PrecisionTaskRegistry, PrecisionTaskSpec, StageTransition, load_precision_task_spec
from .supervisor import PrecisionObservationBundle, PrecisionSkillSupervisor

__all__ = [
    "EntitySpec",
    "PrecisionSkillSpec",
    "PrecisionTaskRegistry",
    "PrecisionTaskSpec",
    "StageTransition",
    "load_precision_task_spec",
    "LocalGeometryError",
    "RingGraspLocalizer",
    "RingSpokeAlignLocalizer",
    "RECOVERY_MAINLINE_NAME",
    "RECOVERY_MAINLINE_CHECKPOINT",
    "RECOVERY_MAINLINE_DATASET",
    "RECOVERY_MAINLINE_REPORT",
    "RUNTIME_FAILURE_TRACE_ROOT",
    "RUNTIME_FAILURE_DATASET_ROOT",
    "BASIN_RECOVERY_DATASET",
    "BASIN_RECOVERY_CLOSED_LOOP_REPORT",
    "GuardedSlideController",
    "GraspContactController",
    "RecoveryFSM",
    "RecoveryPhase",
    "SkillControlResult",
    "BasinLabel",
    "BasinPullbackPolicyNet",
    "BasinRecoveryConfig",
    "BasinRecoveryDecision",
    "BasinRecoveryMode",
    "BasinRecoverySupervisor",
    "BasinStateEstimatorNet",
    "GraspOnlyBasinPullbackPolicy",
    "BasinAxisCalibration",
    "BasinStateCalibration",
    "BasinStateEstimator",
    "CalibratedGraspBasinEstimator",
    "EstimatedBasinError",
    "FrameRelabelBasinEstimator",
    "ReplayBasinEstimator",
    "ReplayBasinResult",
    "load_basin_state_calibration_report",
    "VisualEvidenceClass",
    "basin_recovery_feature_vector",
    "classify_basin_label",
    "classify_visual_evidence_for_basin",
    "DepthLocalizerJsonlDataset",
    "ForceContactJsonlDataset",
    "build_c2c_vocab",
    "DepthGeometryLocalizerNet",
    "RingFrameLocalizerNet",
    "RingFramePrediction",
    "load_ring_frame_localizer_checkpoint",
    "GraspSkillHeadNet",
    "GraspRecoveryHeadNet",
    "GraspSkillPrediction",
    "LearnedDepthLocalizerAdapter",
    "load_depth_localizer_checkpoint",
    "load_grasp_recovery_checkpoint",
    "augment_recovery_record",
    "augment_recovery_record_replay",
    "build_failure_replay_augmented_records",
    "build_failure_replay_library",
    "build_bucket_tail_replay_augmented_records",
    "build_targeted_augmented_records",
    "load_bias_template",
    "select_hard_trajectories",
    "select_focus_trajectories_by_bucket",
    "ForceContactClassifierNet",
    "LearnedForceClassifierAdapter",
    "load_force_classifier_checkpoint",
    "PrecisionObservationBundle",
    "PrecisionSkillSupervisor",
]
