#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc"
fi
PYTHON_BIN="${PYTHON_BIN:-/home/guoning/my_conda_envs/vla-adapter/bin/python3.10}"
HF_CACHE_ROOT=${HF_CACHE_ROOT:-/mnt/ssd/guoning/hf-cache}
export HF_HOME=${HF_HOME:-$HF_CACHE_ROOT}
export HF_HUB_CACHE=${HF_HUB_CACHE:-$HF_CACHE_ROOT/hub}
export HUGGINGFACE_HUB_CACHE=${HUGGINGFACE_HUB_CACHE:-$HF_CACHE_ROOT/hub}
export TRANSFORMERS_OFFLINE=${TRANSFORMERS_OFFLINE:-1}
export HF_HUB_OFFLINE=${HF_HUB_OFFLINE:-1}
export HF_DATASETS_OFFLINE=${HF_DATASETS_OFFLINE:-1}
COPPELIASIM_ROOT="${COPPELIASIM_ROOT:-$HOME/CoppeliaSim}"
CONDA_LIBSTDCXX="${CONDA_LIBSTDCXX:-/home/guoning/my_conda_envs/vla-adapter/lib/libstdc++.so.6}"
BASE_LD_LIBRARY_PATH="${COPPELIASIM_ROOT}:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu"
COMBINED_LD_LIBRARY_PATH="${BASE_LD_LIBRARY_PATH}"
if [ -n "${LD_LIBRARY_PATH:-}" ]; then
  COMBINED_LD_LIBRARY_PATH="${COMBINED_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}"
fi
COMBINED_LD_PRELOAD="${CONDA_LIBSTDCXX}"
if [ -n "${LD_PRELOAD:-}" ]; then
  COMBINED_LD_PRELOAD="${COMBINED_LD_PRELOAD} ${LD_PRELOAD}"
fi

exec env \
  PYTHONPATH="$ROOT_DIR:${PYTHONPATH:-}" \
  VLA_PLATFORM=RLBENCH \
  HF_HOME=$HF_HOME \
  HF_HUB_CACHE=$HF_HUB_CACHE \
  HUGGINGFACE_HUB_CACHE=$HUGGINGFACE_HUB_CACHE \
  TRANSFORMERS_OFFLINE=$TRANSFORMERS_OFFLINE \
  HF_HUB_OFFLINE=$HF_HUB_OFFLINE \
  HF_DATASETS_OFFLINE=$HF_DATASETS_OFFLINE \
  COPPELIASIM_ROOT="$COPPELIASIM_ROOT" \
  QT_QPA_PLATFORM_PLUGIN_PATH="$COPPELIASIM_ROOT" \
  QT_X11_NO_MITSHM=1 \
  XAUTHORITY="" \
  LD_PRELOAD="$COMBINED_LD_PRELOAD" \
  LD_LIBRARY_PATH="$COMBINED_LD_LIBRARY_PATH" \
  xvfb-run -a \
  "$PYTHON_BIN" "$ROOT_DIR/scripts/collect_dagger_rollouts.py" "$@"
